"""
Digest email engine — decides which digests fire today, gathers papers from the
JSONL archive, builds HTML/plain-text emails and sends them via SMTP.

Driven by config/digests.yaml.  When that file exists the digest engine takes
over email delivery from the legacy single daily email.

Copyright (c) 2026 Yizheng Zhen
Licensed under the MIT License
"""

import logging
from datetime import datetime

from . import history
from .config_loader import load_digest_configs
from .email_sender import _resolve_feed_config, _send_smtp, format_single_paper_html
from .models import Config, DigestConfig, DigestType, FeedConfig, SourceConfig

logger = logging.getLogger(__name__)


# ── Calendar ─────────────────────────────────────────────────


def should_send_today(digest: DigestConfig, today=None) -> bool:
    """Whether this digest should be sent on `today`."""
    today = today or datetime.now().date()
    if digest.frequency == DigestType.WEEKDAY:
        return today.weekday() < 5  # Mon–Fri
    if digest.frequency == DigestType.WEEKLY:
        return today.weekday() == int(digest.schedule.get("weekday", 6))
    if digest.frequency == DigestType.MONTHLY:
        return today.day == int(digest.schedule.get("day_of_month", 1))
    if digest.frequency == DigestType.SEASONAL:
        return today.month % 3 == 1 and today.day == 1  # quarter start
    return False


# ── Email building ───────────────────────────────────────────


def build_digest_email_html(
    digest: DigestConfig,
    pairs: list[tuple],
    sources: dict[str, SourceConfig],
    config: Config,
    feed_configs: dict[str, FeedConfig] | None = None,
) -> str:
    date_str = datetime.now().strftime("%B %d, %Y")
    cards = "".join(
        format_single_paper_html(p, a, sources or {}, feed_configs or {}, rank=i + 1)
        for i, (p, a) in enumerate(pairs)
    )
    website = (
        config.public_website_url or "https://yizhengzhen.github.io/quantum-rss-radar/"
    )

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{digest.name} — {date_str}</title>
<style>
  body {{ font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;
         line-height:1.6; color:#212529; margin:0; padding:0; background:#f5f7fa; }}
  .container {{ max-width:620px; margin:0 auto; padding:20px; }}
  .header {{ background:linear-gradient(135deg,#4A90E2,#2C6FB7); color:#fff;
             padding:26px 30px; text-align:center; border-radius:8px 8px 0 0; }}
  .content {{ background:#fff; padding:28px 30px; border-radius:0 0 8px 8px;
              box-shadow:0 4px 12px rgba(0,0,0,0.08); }}
  .footer {{ text-align:center; margin-top:28px; padding-top:18px;
             border-top:1px solid #E9ECEF; color:#6C757D; font-size:0.85em; }}
</style>
</head>
<body>
<div class="container">

  <div class="header">
    <h1 style="margin:0; font-size:24px;">🔬 Quantum RSS Radar</h1>
    <p style="margin:8px 0 0; opacity:0.9; font-size:15px;">{digest.name} — {date_str}</p>
  </div>

  <div class="content">

    <h2 style="margin:0 0 4px; font-size:20px;">{digest.name}</h2>
    <p style="color:#6C757D; margin:0 0 20px; font-size:14px;">
      AI-ranked by relevance to your research interests
      ({len(pairs)} papers, min score {digest.min_score}).
    </p>

    {cards}

    <div style="text-align:center; margin-top:24px;">
      <a href="{website}"
         style="display:inline-block; background:#4A90E2; color:#fff; padding:12px 28px;
                text-decoration:none; border-radius:4px; font-weight:700; font-size:14px;">
        View Full Website &rarr;
      </a>
    </div>

  </div>

  <div class="footer">
    <p>Auto-generated by Quantum RSS Radar.</p>
    <p style="font-size:0.8em;">&copy; {datetime.now().year} — AI-powered research tracking</p>
  </div>

</div>
</body>
</html>"""


def build_digest_email_text(
    digest: DigestConfig,
    pairs: list[tuple],
    sources: dict[str, SourceConfig],
    feed_configs: dict[str, FeedConfig] | None = None,
) -> str:
    date_str = datetime.now().strftime("%Y-%m-%d")
    lines = [
        "=" * 60,
        f"QUANTUM RSS RADAR — {digest.name}",
        date_str,
        "=" * 60,
        "",
        f"Total papers: {len(pairs)}  (min score: {digest.min_score})",
        "",
        f"TOP {len(pairs)} PAPERS BY SCORE",
        "-" * 40,
        "",
    ]

    for i, (paper, analysis) in enumerate(pairs, 1):
        src_display, _ = _resolve_feed_config(paper, sources or {}, feed_configs or {})
        authors = ", ".join(paper.authors[:3])
        if len(paper.authors) > 3:
            authors += " et al."
        lines += [
            f"{i}. {paper.title}",
            f"   Score: {analysis.relevance_score:.1f}/10",
            f"   Source: {src_display}  |  Direction: {analysis.direction or 'General / Other'}",
            f"   Authors: {authors}",
            f"   TL;DR: {analysis.tldr}",
            f"   Link: {paper.link}",
            "",
        ]

    lines += [
        "-" * 40,
        "Auto-generated by Quantum RSS Radar.",
        f"(c) {datetime.now().year}",
        "",
    ]
    return "\n".join(lines)


# ── Orchestrated sending ─────────────────────────────────────


def send_digests(
    config_dir: str = "config",
    config: Config | None = None,
    sources: dict[str, SourceConfig] | None = None,
    feed_configs: dict[str, FeedConfig] | None = None,
    archive_dir: str | None = None,
    today=None,
) -> dict[str, bool]:
    """Send all enabled digests that are due today.

    Returns:
        {digest_id: sent_ok}
    """
    if config is None:
        from .config_loader import load_config

        config = load_config()

    if not config.email_enabled:
        logger.info("Email sending disabled — skipping digests")
        return {}

    digests = load_digest_configs(config_dir)
    enabled = [d for d in digests if d.enabled]
    if not enabled:
        logger.info("No enabled digests found")
        return {}

    archive_dir = archive_dir or config.archive_dir
    records = history.load_jsonl_archive(archive_dir)
    today = today or datetime.now().date()

    results: dict[str, bool] = {}
    for digest in enabled:
        if not should_send_today(digest, today):
            logger.info(f"Digest '{digest.id}' not scheduled for {today} — skipping")
            continue

        selected = history.filter_by_digest(records, digest, today)
        pairs = history.records_to_pairs(selected)
        if not pairs:
            logger.warning(
                f"Digest '{digest.id}' is due but no papers matched — skipping"
            )
            results[digest.id] = False
            continue

        subject = digest.subject_template.format(
            name=digest.name, date=today.strftime("%Y-%m-%d")
        )
        html = build_digest_email_html(
            digest, pairs, sources or {}, config, feed_configs
        )
        text = build_digest_email_text(digest, pairs, sources or {}, feed_configs)

        ok = _send_smtp(subject, html, text, config)
        logger.info(
            f"Digest '{digest.id}' ({digest.name}) sent: {ok} ({len(pairs)} papers)"
        )
        results[digest.id] = ok

    return results
