"""
Data models for the Quantum RSS Radar system.

Copyright (c) 2026 Yizheng Zhen
Licensed under the MIT License
"""

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class PaperSource(str, Enum):
    """Sources of research papers."""

    ARXIV = "arxiv"
    APS = "aps"
    NATURE = "nature"
    SCIENCE = "science"
    IEEE = "ieee"
    ACM = "acm"
    SPRINGER = "springer"
    OTHER = "other"


class UpdateFrequency(str, Enum):
    """How often a feed fires, and which email group it joins.

    Feeds sharing the same update_frequency are merged into ONE email:
      * daily   → every day
      * weekday → Mon–Fri (e.g. the arXiv group)
      * weekly  → every Sunday (weekend journal roundup)
      * monthly → 1st of month (e.g. the Nature/Science group)
      * season  → quarter start (1/1, 4/1, 7/1, 10/1)
    """

    DAILY = "daily"
    WEEKDAY = "weekday"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    SEASON = "season"


class Paper(BaseModel):
    """Represents a research paper from RSS feed.

    Note: 'category' is NOT stored here.  The LLM assigns a
    'direction' during semantic analysis based on the user's
    research interests (see PaperAnalysis.direction).
    """

    id: str = Field(..., description="Unique identifier for the paper")
    title: str = Field(..., description="Paper title")
    authors: list[str] = Field(default_factory=list, description="List of authors")
    abstract: str = Field(..., description="Paper abstract")
    link: str = Field(..., description="URL to paper or arXiv page")
    published: datetime = Field(..., description="Publication date")
    source: PaperSource = Field(..., description="Source of the paper")
    feed_name: str = Field(..., description="Name of the RSS feed")
    rss_fetch_date: datetime = Field(
        default_factory=datetime.now, description="RSS feed fetch time"
    )
    tags: list[str] = Field(default_factory=list, description="Keywords tags, max 5")
    doi: str | None = Field(None, description="Normalized DOI (primary dedup key)")
    alternate_link: str | None = Field(
        None,
        description="Alternate link kept after DOI merge (e.g. arXiv version of a published paper)",
    )
    raw_data: dict[str, Any] = Field(default_factory=dict, description="Raw RSS data")

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
        }


class DeepReadResult(BaseModel):
    """Deep reading analysis result for high-score papers.

    Generated by arxiv_deep_reader.py for papers with relevance_score
    >= min_relevance_score. Attached to PaperAnalysis.deep_read.
    """

    paper_id: str = Field(..., description="ID of the analyzed paper")
    detailed_summary: str = Field("", description="2-3 paragraph comprehensive summary")
    key_contributions: list[str] = Field(
        default_factory=list, description="3-5 specific contributions"
    )
    methodology_analysis: str = Field("", description="Detailed analysis of methods")
    results_analysis: str = Field(
        "", description="Analysis of key results with specific numbers"
    )
    strengths: list[str] = Field(
        default_factory=list, description="2-4 specific strengths"
    )
    limitations: list[str] = Field(
        default_factory=list, description="1-3 limitations or areas for improvement"
    )
    connections_to_research: str = Field(
        "", description="How this connects to researcher's interests"
    )
    overall_assessment: str = Field(
        "", description="Final verdict on significance, novelty, quality"
    )

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
        }


class PaperAnalysis(BaseModel):
    """AI analysis results for a paper."""

    paper_id: str = Field(..., description="ID of the analyzed paper")
    relevance_score: float = Field(..., ge=0, le=10, description="Relevance score 0-10")
    recommendation: bool = Field(..., description="Whether to recommend (yes/no)")
    summary: dict[str, str] = Field(..., description="Structured summary")
    keywords: list[str] = Field(default_factory=list, description="Extracted keywords")
    direction: str = Field(
        "", description="Research direction classified by LLM based on user interests"
    )
    processing_time: datetime = Field(
        default_factory=datetime.now, description="When analysis was performed"
    )
    deep_read: DeepReadResult | None = Field(
        None, description="Optional deep reading analysis for high-score papers"
    )

    # Structured summary fields (also included in summary dict)
    @property
    def tldr(self) -> str:
        return self.summary.get("tldr", "")

    @property
    def motivation(self) -> str:
        return self.summary.get("motivation", "")

    @property
    def method(self) -> str:
        return self.summary.get("method", "")

    @property
    def result(self) -> str:
        return self.summary.get("result", "")

    @property
    def conclusion(self) -> str:
        return self.summary.get("conclusion", "")

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
        }


class Config(BaseModel):
    """System configuration."""

    llm_provider: str = Field(
        "openai", description="LLM provider: openai, deepseek, or custom"
    )
    llm_model: str = Field("gpt-4-turbo-preview", description="LLM model name")
    llm_api_key: str | None = Field(None, description="LLM API key")
    llm_base_url: str | None = Field(
        None, description="Custom API base URL for OpenAI-compatible providers"
    )

    email_enabled: bool = Field(False, description="Whether to send emails")
    email_sender: str | None = Field(None, description="Sender email address")
    email_recipient: str | None = Field(None, description="Recipient email address")
    email_smtp_server: str | None = Field(None, description="SMTP server")
    email_smtp_port: int | None = Field(587, description="SMTP port")
    email_smtp_username: str | None = Field(None, description="SMTP username")
    email_smtp_password: str | None = Field(None, description="SMTP password")

    max_papers_per_feed: int = Field(50, description="Max papers to fetch per feed")
    min_relevance_score: float = Field(
        5.0, description="Minimum score for recommendation"
    )
    archive_dir: str = Field(
        "data/all",
        description="Directory of JSONL archive for digest/quarterly aggregation",
    )
    quarter_window_days: int = Field(
        90, description="Quarter window in days for the web quarterly view"
    )
    quarterly_top_n: int = Field(
        50,
        description="Top-N papers per category (preprints/publications) in the quarterly web view",
    )

    output_dir: str = Field("data", description="Base output directory")
    web_dir: str = Field("web_output", description="Website output directory")

    class Config:
        extra = "allow"  # Allow dynamic attributes

    def __init__(self, **data):
        super().__init__(**data)
        # Initialize dynamic attributes
        self._raw_config = {}
        self._jekyll_site_dir = "jekyll_site/_site"
        self._rss_timeout = 30
        self._llm_timeout = 60
        self._llm_temperature = 0.1
        self._llm_max_tokens = 2500
        self._llm_reasoning_effort = "low"
        self._debug = False
        self._deep_read_enabled = True
        self._llm_cache_enabled = True
        self._research_directions = ""
        self._public_website_url = ""

    @property
    def jekyll_site_dir(self) -> str:
        """Get Jekyll site directory."""
        return getattr(self, "_jekyll_site_dir", "jekyll_site/_site")

    @property
    def rss_timeout(self) -> int:
        """Get RSS fetch timeout."""
        return getattr(self, "_rss_timeout", 30)

    @property
    def llm_timeout(self) -> int:
        """Get LLM API timeout."""
        return getattr(self, "_llm_timeout", 60)

    @property
    def llm_temperature(self) -> float:
        """Get LLM temperature."""
        return getattr(self, "_llm_temperature", 0.1)

    @property
    def llm_max_tokens(self) -> int:
        """Get LLM max output tokens.

        Reasoning models (e.g. deepseek-v4-flash) may spend a large part of
        this budget on internal reasoning. If it is too small, the model runs
        out of tokens before writing the JSON answer and returns empty content.
        """
        return getattr(self, "_llm_max_tokens", 2500)

    @property
    def llm_reasoning_effort(self) -> str:
        """Get LLM reasoning_effort knob ('low'/'medium'/'high' or '' to disable).

        deepseek-v4-flash keeps 'thinking' until it exhausts max_tokens, which
        both slows every call and yields EMPTY content on long chain-of-thought.
        Capping it low makes scoring fast and prevents the empty-response bug.
        """
        return getattr(self, "_llm_reasoning_effort", "low")

    @property
    def debug(self) -> bool:
        """Get debug mode."""
        return getattr(self, "_debug", False)

    @property
    def deep_read_enabled(self) -> bool:
        """Get deep reading enabled flag."""
        return getattr(self, "_deep_read_enabled", True)

    @property
    def llm_cache_enabled(self) -> bool:
        """Get LLM cache enabled flag."""
        return getattr(self, "_llm_cache_enabled", True)

    @property
    def research_directions(self) -> str:
        """Get research directions string."""
        return getattr(self, "_research_directions", "")

    @property
    def public_website_url(self) -> str:
        """Get public website URL."""
        return getattr(self, "_public_website_url", "")

    @property
    def raw_config(self) -> dict:
        """Get raw configuration data."""
        return getattr(self, "_raw_config", {})


class FeedConfig(BaseModel):
    """Configuration for an RSS feed.

    Note: 'category' has been removed.  The LLM assigns a
    research 'direction' during semantic analysis.

    Each feed can optionally specify its own display_name and color
    for per-journal colour tags in email and website.  Falls back to
    the source-level config if not provided.
    """

    name: str = Field(..., description="Feed display name")
    url: str = Field(..., description="RSS feed URL")
    source: PaperSource = Field(..., description="Source type")
    display_name: str | None = Field(
        None, description="Journal display name (overrides source-level display_name)"
    )
    color: str | None = Field(
        None,
        description="Hex colour for this journal's tag (overrides source-level color)",
    )
    max_items: int = Field(
        -1, description="Max papers to recommend per run (-1 for unlimited)"
    )
    min_score: float = Field(7.0, description="Minimum relevance score to include")
    update_frequency: UpdateFrequency = Field(
        UpdateFrequency.DAILY, description="How often this feed fires (email group)"
    )

    def is_due(self, today=None) -> bool:
        """Whether this feed fires on `today` (per its update_frequency).

        Shared by per-source scheduled fetching (rss_fetcher) and the email
        engine (digest_engine).
        """
        today = today or datetime.now().date()
        if isinstance(today, datetime):
            today = today.date()
        freq = self.update_frequency
        if freq == UpdateFrequency.DAILY:
            return True
        if freq == UpdateFrequency.WEEKDAY:
            return today.weekday() < 5  # Mon–Fri
        if freq == UpdateFrequency.WEEKLY:
            return today.weekday() == 6  # Sunday (weekend roundup)
        if freq == UpdateFrequency.MONTHLY:
            return today.day == 1
        if freq == UpdateFrequency.SEASON:
            return today.month % 3 == 1 and today.day == 1  # quarter start
        return False

    def window_days(self, today=None) -> int:
        """Collection window (days) derived from this feed's frequency.

        * weekday: Monday covers Fri–Sun (3d), other weekdays 1d
        * weekly → 7d, monthly → 30d, season → 90d, daily → 1d
        """
        today = today or datetime.now().date()
        if isinstance(today, datetime):
            today = today.date()
        freq = self.update_frequency
        if freq == UpdateFrequency.WEEKDAY:
            return 3 if today.weekday() == 0 else 1
        if freq == UpdateFrequency.WEEKLY:
            return 7
        if freq == UpdateFrequency.MONTHLY:
            return 30
        if freq == UpdateFrequency.SEASON:
            return 90
        return 1


class SourceConfig(BaseModel):
    """Configuration for a paper source (displayed on website)."""

    display_name: str = Field(..., description="Display name for UI (e.g. 'arXiv')")
    color: str = Field(..., description="Hex color for the source tag")
